/**
 * This constant list commons environment variables that are sensitive
 * and should be filtered from public exposed configs.
 */
export const COMMON_SENSITIVE_ENVIRONMENT_VARIABLES = [
  // AWS credentials
  'AWS_ACCESS_KEY_ID',
  'AWS_SECRET_ACCESS_KEY',
  'AWS_REGION',
  'AWS_AVAILABILITY_ZONES',

  // Terraform credentials
  'TERRAFORM_REMOTE_BACKEND_HOST',
  'TERRAFORM_REMOTE_BACKEND_ORG',
  'TERRAFORM_REMOTE_BACKEND_WORKSPACE',
  'TERRAFORM_REMOTE_BACKEND_TOKEN',

  // Postgres credentials
  'POSTGRES_USER',
  'POSTGRES_PASSWORD',
  'POSTGRES_DB',
  'POSTGRES_HOST',
  'POSTGRES_PORT',
  'POSTGRES_SCHEMA',
  'DATABASE_URL',

  // S3 credentials
  'FILE_STORAGE_ACCESS_KEY',
  'FILE_STORAGE_SECRET_KEY',
  'FILE_STORAGE_ENDPOINT',
  'FILE_STORAGE_PORT',
  'FILE_STORAGE_DEFAULT_BUCKET',

  // Elasticsearch credentials
  'XPACK_MANAGEMENT_ELASTICSEARCH_CLOUD_ID',
  'XPACK_MANAGEMENT_ELASTICSEARCH_CLOUD_AUTH',
  'XPACK_MANAGEMENT_PIPELINE_ID',

  // Mailjet credentials
  'MAILER_PUBLIC_API_KEY',
  'MAILER_PRIVATE_API_KEY',

  // RabbitMQ credentials
  'MESSAGE_BROKER_DOMAIN',
  'MESSAGE_BROKER_PORT',
  'MESSAGE_BROKER_PROTOCOL',
  'MESSAGE_BROKER_USER',
  'MESSAGE_BROKER_PASSWORD',

  // Session secrets
  'COOKIE_SECRET',
  'JWT_SECRET',

  // Custom front-end nginx paths
  'HTML_INDEX_PATH',
];
