version: 2

registries:
  tractr-registry:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{secrets.GH_TOKEN}}

updates:
  # Keep mix dependencies up to date
  - package-ecosystem: 'npm'
    directory: '/'
    registries:
      - tractr-registry
    schedule:
      interval: 'weekly'
    assignees:
      - 'tractr/developers'
    reviewers:
      - 'tractr/developers'
    labels:
      - 'dependabot-update'
    commit-message:
      prefix: 'chore(deps)'
      prefix-development: 'chore(dev-deps)'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: 'daily'
    commit-message:
      prefix: 'chore(action)'
