version: '3'

services:
  #------------------------------------------------
  # Database
  #------------------------------------------------
  database:
    image: postgres:13-alpine
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    volumes:
      - database-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  #------------------------------------------------
  # File storage
  #------------------------------------------------
  minio:
    image: minio/minio
    command: server /export
    ports:
      - 9000:9000
    environment:
      - MINIO_ACCESS_KEY=${TRACTR_FILE_STORAGE_ACCESS_KEY}
      - MINIO_SECRET_KEY=${TRACTR_FILE_STORAGE_SECRET_KEY}
    volumes:
      - s3-data:/export

volumes:
  database-data:
  s3-data:
