import { Provider } from '@nestjs/common';
import {
  USER_AUTHORIZED_SERVICE_PROVIDER,
  TASK_AUTHORIZED_SERVICE_PROVIDER,
} from './providers';

export const AUTHORIZED_SERVICES_PROVIDERS: Provider[] = [
  ...USER_AUTHORIZED_SERVICE_PROVIDER,
  ...TASK_AUTHORIZED_SERVICE_PROVIDER,
];
