export const defaultFields = {
  name: 'id',
  type: 'string',
  subtype: null,
  reference: null,
  primary: true,
  unique: false,
  label: false,
  nullable: false,
  multiple: false,
  embedded: false,
  searchable: true,
  sortable: true,
  hidden: false,
  internal: true,
  restricted: false,
  ownership: false,
};
