import { ValidationPipe } from '@nestjs/common';
import { NestFactory } from '@nestjs/core';
import { DocumentBuilder, SwaggerModule } from '@nestjs/swagger';
import * as cookieParser from 'cookie-parser';
import * as morgan from 'morgan';

import { AppModule } from './app/app.module';

import { Logger } from '@tractr/nestjs-core';

// Bootstrap the main application
async function bootstrap() {
  const port = process.env.PORT || 3000;
  const globalPrefix = 'api';

  // Instanciate nest app
  const app = await NestFactory.create(AppModule);

  // Set custom logger service
  const logger = await app.resolve(Logger);
  app.useLogger(logger);
  app.setGlobalPrefix(globalPrefix);

  app.use(morgan('combined'));

  app.use(cookieParser('myScret'));

  // Set global validation pipe
  app.useGlobalPipes(
    new ValidationPipe({
      whitelist: true,
      forbidNonWhitelisted: true,
      transform: true,
      transformOptions: {
        enableImplicitConversion: true,
      },
    }),
  );

  // Set swagger documentation
  const swaggerOptions = new DocumentBuilder()
    .setTitle('Hapify boilerplate')
    .setDescription('This is the REST API documentation generated by Swagger')
    .setVersion('1.0')
    .addTag('swagger')
    .build();

  const swaggerDocument = SwaggerModule.createDocument(app, swaggerOptions);
  SwaggerModule.setup('api', app, swaggerDocument);

  // Start app and define port
  await app.listen(port, () => {
    logger.log(`Listening at http://localhost:${port}/${globalPrefix}`);
  });
}

bootstrap().catch((e) => {
  console.error('Failed to start the server. See the error below.');
  console.error(e);
});
