version: '3'

services:
  #------------------------------------------------
  # Database
  #------------------------------------------------
  database:
    image: postgres:13-alpine
    ports:
      - '${TRACTR_POSTGRESQL_PORT:-5432}:5432'
    volumes:
      - database-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${TRACTR_POSTGRESQL_USER}
      - POSTGRES_PASSWORD=${TRACTR_POSTGRESQL_PASSWORD}
      - POSTGRES_DB=${TRACTR_POSTGRESQL_DB}

volumes:
  database-data:
