name: Test the Getting Started guide

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:

jobs:
  test:
    name: Test the steps in the Getting Started guide

    # Our code will run on node 16 and Linux
    strategy:
      matrix:
        node: [16.x]
        os: [ubuntu-20.04]

    runs-on: '${{ matrix.os }}'

    steps:
      # First we checkout the code
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      # Build the project
      - name: Install dependencies and generate files
        uses: tractr/traxion/.github/actions/setup@main
        with:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Run getting started build script
        run: |
          tools/getting-started/build.sh

      - name: Run getting started test script
        run: |
          tools/getting-started/test.sh
