name: pr commitlint

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v3.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
