name: Stack test the API start

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:

jobs:
  test:
    name: Test the start of the api

    # Our code will run on node 16 and Linux
    strategy:
      matrix:
        node: [16.x]
        os: [ubuntu-20.04]

    runs-on: ['${{ matrix.os }}']

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: api
          POSTGRES_PASSWORD: postgres
        ports: ['5432:5432']
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s
          --health-retries 10

    steps:
      # First we checkout the code
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      # We install our dependencies and generate the files
      - name: Install dependencies and generate files
        uses: tractr/stack/.github/actions/setup@main
        with:
          registryUrl: 'https://npm.pkg.github.com'
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create .env file
        run: |
          echo "API_URL=http://localhost:4200/api" > .env

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          start: npx nx serve api
          command: npx nx e2e pwa-e2e --record
          record: true
          install: false
          wait-on: 'http://localhost:3000/api'
        env:
          # statement_cache_size allow the api to not throw an error when the database is truncate then seed
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/api?statement_cache_size=0
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
